### PR TITLE
feat: add disabled dates list or callback prop

### PR DESCRIPTION
**Pull request by mitri-dvp**
## Feature: Disable Custom Dates
In support of adding a feature that allows disabling custom dates I've added a prop `disabledDates` that accepts an array of dates (`DateType[]`) or a validation function (`(date: dayjs.Dayjs) => boolean`)

This change is very similar to [JHPG PR](https://github.com/farhoudshapouran/react-native-ui-datepicker/pull/99) but with the added compatibility for the disabled dates list inspired by the handling found in [Stephy CalendarPicker](https://github.com/stephy/CalendarPicker) project and adapted to use existing functionality like the `areDatesOnSameDay` method

An example of both was added to the example app `App.tsx`.

### CODE REVIEW

**Comment by mitri-dvp** [comment]
Hi JHPG I’ve liked your approach and have extended the functionality by adding compatibility for disabling dates based on a disabled dates list. Here’s my [PR](https://github.com/farhoudshapouran/react-native-ui-datepicker/pull/102).

**Comment by timdimas** [comment]
I noticed a small bug in your code where if you had minDate or maxDate they wouldn't work and they would be overlapped by disabledDates here is a fix for that:
```ts let disabled = false;
  if (minDate) {
    disabled = disabled || date < getDate(minDate);
  }
  if (maxDate) {
    disabled = disabled || date > getDate(maxDate);
  }
  if (disabledDates) {
    if (Array.isArray(disabledDates)) {
      const dates = disabledDates.filter((disabledDate) =>
        areDatesOnSameDay(date, disabledDate)
      );
      disabled = disabled || dates.length > 0;
    } else if (disabledDates instanceof Function) {
      disabled = disabled || disabledDates(date);
    }
  }

**Comment by mitri-dvp** [comment]
@timdimas Good catch, I'll update the PR with this fix. Since it's getting a little messy I'll refactor it into a new `isDateDisabled` helper method, similar to the other ones.

**Comment by timdimas** [comment]
@mitri-dvp Great stuff, also i have been thinking, if you have the mode="range" and you put a range before and after the disabled dates, the disabled dates will be selected even thought they are disabled. Even thought it's a simple fix on the onChange function where you check for your disabled dates and if they overlap return null, i feel like this logic should be applied automatically, when you have disabled dates. I will look into in more and try to help you

**Review by farhoudshapouran — APPROVED** [review]
This approach covers previous PR's 👍🏻

**Pull request merged**
