### PR TITLE
Fix: style on selected range

### PR DESCRIPTION
**Pull request by zdinidz**
i wanna fix bug on styling selected date range 
from this 
image

to this
image

### CODE REVIEW

**Comment by zdinidz** [comment]
i add condition for selected range with single and same day 

from this
image

to be this
image

**Comment by Yzzzed** [comment]
same problem. Hope it can be fixed soon.

**Comment by gtarnowski** [comment]
any chance to merge it :) ?

**Comment by zdinidz** [comment]
> any chance to merge it :) ?

i think yes, how to merge it?

**Review by jtsimoes — APPROVED** [review]

**Comment by jtsimoes** [comment]
LGTM!
However, there is still a related issue with the selected range when `displayFullDays = true`:

| Start date is in the previous month | End date is in the next month | Start date is in the previous month and end date is in the next month | Start date and end date are in the current month |
| :-: | :-: | :-: | :-: |
| bug_2 | bug_3 | bug_1 | bug_4 |
|❌|❌|❌|✅|

Any idea how to fix it? If so, wouldn't be a good idea to include it in this PR too?

**Comment by zdinidz** [comment]
image
image
image
i have fix it but i haven't push it

**Review by farhoudshapouran — APPROVED** [review]

**Comment by Yzzzed** [comment]
> LGTM! However, there is still a related issue with the selected range when `displayFullDays = true`:
> 
> Start date is in the previous month	End date is in the next month	Start date is in the previous month and end date is in the next month	Start date and end date are in the current month
> bug_2	bug_3	bug_1	bug_4
> ❌	❌	❌	✅
> Any idea how to fix it? If so, wouldn't be a good idea to include it in this PR too?

i have fixed it and created a new pr. https://github.com/farhoudshapouran/react-native-ui-datepicker/pull/113

**Pull request merged**
